//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHVBDQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUCNANG
    {
        public CHUCNANG()
        {
            this.NHOMNGUOIDUNGs = new HashSet<NHOMNGUOIDUNG>();
        }
    
        public string MaChucNang { get; set; }
        public string TenChucNang { get; set; }
        public string TenManHinhDuocLoad { get; set; }
    
        public virtual ICollection<NHOMNGUOIDUNG> NHOMNGUOIDUNGs { get; set; }
    }
}
