//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHVBDQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPDV
    {
        public string SoPhieu { get; set; }
        public string MaLDV { get; set; }
        public Nullable<double> ChiPhiRieng { get; set; }
        public int SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public double TraTruoc { get; set; }
        public Nullable<double> ConLai { get; set; }
        public bool TinhTrang { get; set; }
    
        public virtual LOAIDICHVU LOAIDICHVU { get; set; }
        public virtual PHIEUDICHVU PHIEUDICHVU { get; set; }
    }
}
