//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHVBDQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVT
    {
        public DVT()
        {
            this.LOAISANPHAMs = new HashSet<LOAISANPHAM>();
        }
    
        public string MaDVT { get; set; }
        public string TenDVT { get; set; }
    
        public virtual ICollection<LOAISANPHAM> LOAISANPHAMs { get; set; }
    }
}
