//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHVBDQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public KHACHHANG()
        {
            this.PHIEUBANHANGs = new HashSet<PHIEUBANHANG>();
            this.PHIEUDICHVUs = new HashSet<PHIEUDICHVU>();
        }
    
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string SDT { get; set; }
    
        public virtual ICollection<PHIEUBANHANG> PHIEUBANHANGs { get; set; }
        public virtual ICollection<PHIEUDICHVU> PHIEUDICHVUs { get; set; }
    }
}
