//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHVBDQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIDICHVU
    {
        public LOAIDICHVU()
        {
            this.CTPDVs = new HashSet<CTPDV>();
        }
    
        public string MaLDV { get; set; }
        public string TenLDV { get; set; }
        public double DonGia { get; set; }
    
        public virtual ICollection<CTPDV> CTPDVs { get; set; }
    }
}
