//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHVBDQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUBANHANG
    {
        public PHIEUBANHANG()
        {
            this.CTPBHs = new HashSet<CTPBH>();
        }
    
        public string SoPhieu { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string MaKH { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        public virtual ICollection<CTPBH> CTPBHs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
