//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHVBDQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUMUAHANG
    {
        public PHIEUMUAHANG()
        {
            this.CTPMHs = new HashSet<CTPMH>();
        }
    
        public string SoPhieu { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string MaNCC { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        public virtual ICollection<CTPMH> CTPMHs { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
