//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHVBDQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.BCTONKHOes = new HashSet<BCTONKHO>();
            this.CTPBHs = new HashSet<CTPBH>();
            this.CTPMHs = new HashSet<CTPMH>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string MaLSP { get; set; }
        public double DonGia { get; set; }
        public int TonKho { get; set; }
    
        public virtual ICollection<BCTONKHO> BCTONKHOes { get; set; }
        public virtual ICollection<CTPBH> CTPBHs { get; set; }
        public virtual ICollection<CTPMH> CTPMHs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
